import { BaseEntity } from "./BaseEntity";

export class Budgetvarreport001mb extends BaseEntity {
    varId?: number;
    fiscalYear?: number;
    period?: string;
    company?: string;
    centerName?: string;
    bgaccountType?: string;
    actualjan?: string | null;
    variancejan?: string | null;
    targetjan?: string | null;
    actualfeb?: string | null;
    variancefeb?: string | null;
    targetfeb?: string | null;
    actualmar?: string | null;
    variancemar?: string | null;
    targetmar?: string | null;
    actualapr?: string | null;
    varianceapr?: string | null;
    targetapr?: string | null;
    actualmay?: string | null;
    variancemay?: string | null;
    targetmay?: string | null;
    actualjun?: string | null;
    variancejun?: string | null;
    targetjun?: string | null;
    actualjul?: string | null;
    variancejul?: string | null;
    targetjul?: string | null;
    actualaug?: string | null;
    varianceaug?: string | null;
    targetaug?: string | null;
    actualsep?: string | null;
    variancesep?: string | null;
    targetsep?: string | null;
    actualoct?: string | null;
    varianceoct?: string | null;
    targetoct?: string | null;
    actualnov?: string | null;
    variancenov?: string | null;
    targetnov?: string | null;
    actualdec?: string | null;
    variancedec?: string | null;
    targetdec?: string | null;
    totalTarget?: string | null;
    totalActual?: string | null;
    totalVariance?: string | null;
}
